[build]
  command = "echo 'hello Netlify build'"
  publish = "fixtures/publishDir"
  functions = "fixtures/functions"

[[plugins]]
package = "@netlify/plugin-local-install-core"
[[plugins]]
  package = "./fixtures/generator"
[[plugins]]
  package = "./index.js"
  [plugins.inputs]
    exclude = ["/search.html"]
    debugMode = true
    [build]
  functions = 'functions' # must specify a functions folder for this to work
[[plugins]]
  package = 'netlify-plugin-search-index'
  # all inputs are optional, we just show you the defaults below
  # [plugins.inputs]
    # exclude = ["/ignore-this-file.html"] # don't index this file
    # generatedFunctionName = 'search' # change the name of generated folder in case of conflicts, use `null` to turn off
    # publishDirJSONFileName = 'searchIndex' # also use null to turn off